### ISSUE TITLE
backgroundCheckUpdate执行block时weakself为nil

### ISSUE THREAD

**Issue by Dengni8023** [dengjunwen/JWNetAutoCache#2]
这个方法内部的执行block有问题吧？
断点调试进入block时weakself为nil，后续的操作都没意义了

**Comment by dengjunwen** [comment]
不好意思。。请问在什么情况下出现这样的情况呢。。我无法重现这样的问题。是否可以将demo发给我看下。

**Comment by Dengni8023** [comment]
Demo就是你放在GitHub上的这个项目，我修改了一下证书配置，其他没做修改。首次build没回进入断点，加载完成后第二次build就会进断点


![snapshot](https://cloud.githubusercontent.com/assets/4497001/22821670/1bb81fe6-efb7-11e6-85e2-7ebec47f47c2.png)
